/**
 * ARCHAEOMap - Curated Archaeological Survey Dataset
 * Authentic field survey observations across 5 archaeological sectors (Sites A-E)
 * Optimized for GIS spatial clustering (DBSCAN), stratigraphy analysis, and museum taxonomy.
 */

const INITIAL_ARTIFACTS = [
  {
    id: "ARC-2026-001",
    name: "Terracotta Red-Ware Vessel Fragment",
    type: "Pottery",
    material: "Terracotta",
    period: "Ancient",
    site: "Site A",
    excavationArea: "Citadel Sector - Trench IV",
    layer: "Stratum III (Compact Ash Fill)",
    depth: 1.4,
    latitude: 20.2961,
    longitude: 85.8245,
    status: "Documented",
    description: "Wheel-turned rim and shoulder sherd of a storage jar displaying incised geometric chevron bands. High oxidation firing with fine mineral temper. Diagnostic of Phase II urban occupation.",
    imageUrl: "https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=800&q=80",
    dateRecorded: "2026-02-14",
    recordedBy: "Dr. A. Sen (Senior Field Archaeologist)"
  },
  {
    id: "ARC-2026-002",
    name: "Punch-Marked Silver Karshapana",
    type: "Coin",
    material: "Copper",
    period: "Ancient",
    site: "Site A",
    excavationArea: "Citadel Sector - Trench I",
    layer: "Stratum II (Residential Floor Level)",
    depth: 0.9,
    latitude: 20.2970,
    longitude: 85.8260,
    status: "Documented",
    description: "Square-clipped copper alloy coin bearing faint punch marks including solar symbol, six-armed wheel, and arched hill. Characteristic of late Mauryan provincial currency.",
    imageUrl: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=800&q=80",
    dateRecorded: "2026-02-15",
    recordedBy: "M. Vance (Numismatics Specialist)"
  },
  {
    id: "ARC-2026-003",
    name: "Sandstone Figurine Torso",
    type: "Sculpture",
    material: "Stone",
    period: "Ancient",
    site: "Site B",
    excavationArea: "Southern Terraces - Trench VII",
    layer: "Stratum IV (Monumental Foundation Trench)",
    depth: 1.8,
    latitude: 20.2905,
    longitude: 85.8290,
    status: "Documented",
    description: "Buff sandstone carving representing female deity or attendant torso. Graceful tribhanga posture, ornate beaded waist girdle (mekhala), and remnant drapery folds.",
    imageUrl: "https://images.unsplash.com/photo-1544967082-d9d25d867d66?auto=format&fit=crop&w=800&q=80",
    dateRecorded: "2026-02-18",
    recordedBy: "Dr. K. Rath (Iconography Lead)"
  },
  {
    id: "ARC-2026-004",
    name: "Socketed Bronze Spearhead",
    type: "Tool",
    material: "Bronze",
    period: "Ancient",
    site: "Site A",
    excavationArea: "Citadel Sector - Trench II",
    layer: "Stratum III (Armory Destruction Layer)",
    depth: 1.6,
    latitude: 20.2965,
    longitude: 85.8252,
    status: "Documented",
    description: "Cast bronze leaf-shaped blade with distinct median ridge terminating in a hollow conical socket. Two rivet perforations intact; displays heavy verdigris crust.",
    imageUrl: "https://images.unsplash.com/photo-1595769816263-9b910be24d5f?auto=format&fit=crop&w=800&q=80",
    dateRecorded: "2026-02-20",
    recordedBy: "R. Thorne (Metallurgy Team)"
  },
  {
    id: "ARC-2026-005",
    name: "Carnelian & Agate Beaded Necklace Segment",
    type: "Jewelry",
    material: "Stone",
    period: "Ancient",
    site: "Site B",
    excavationArea: "Southern Terraces - Trench IX",
    layer: "Stratum II (Grave Cut 14)",
    depth: 1.1,
    latitude: 20.2912,
    longitude: 85.8282,
    status: "Documented",
    description: "Fourteen etched carnelian micro-beads with white alkali geometric loops, accompanied by three banded agate barrel beads. Precision diamond-tipped drill borings.",
    imageUrl: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=800&q=80",
    dateRecorded: "2026-02-22",
    recordedBy: "Dr. A. Sen (Senior Field Archaeologist)"
  },
  {
    id: "ARC-2026-006",
    name: "Early Brahmi Inscribed Clay Sealing",
    type: "Inscription",
    material: "Clay",
    period: "Ancient",
    site: "Site A",
    excavationArea: "Citadel Sector - Trench III",
    layer: "Stratum II (Administrative Repository)",
    depth: 0.8,
    latitude: 20.2958,
    longitude: 85.8240,
    status: "Documented",
    description: "Circular unbaked clay bulla with clear string impression on reverse. Obverse displays four characters in early Ashokan Brahmi reading 'Dharmasa', beneath a bull emblem.",
    imageUrl: "https://images.unsplash.com/photo-1569683795645-b62e50fbf103?auto=format&fit=crop&w=800&q=80",
    dateRecorded: "2026-02-24",
    recordedBy: "Prof. H. Sahoo (Epigraphist)"
  },
  {
    id: "ARC-2026-007",
    name: "Kiln-Fired Fortification Brick",
    type: "Brick",
    material: "Terracotta",
    period: "Ancient",
    site: "Site A",
    excavationArea: "Citadel Rampart - North Bastion",
    layer: "Stratum IV (Rampart Revetment)",
    depth: 2.3,
    latitude: 20.2974,
    longitude: 85.8256,
    status: "Documented",
    description: "Standard modular burnt brick conforming to classic 1:2:4 ratio (42 x 21 x 10.5 cm). Finger-drag drying marks and straw temper voids visible across bedding plane.",
    imageUrl: "https://images.unsplash.com/photo-1590069261209-f8e9b8642343?auto=format&fit=crop&w=800&q=80",
    dateRecorded: "2026-02-25",
    recordedBy: "T. Bennett (Survey Architect)"
  },
  {
    id: "ARC-2026-008",
    name: "Northern Black Polished Ware (NBPW) Sherd",
    type: "Pottery",
    material: "Clay",
    period: "Ancient",
    site: "Site A",
    excavationArea: "Citadel Sector - Trench V",
    layer: "Stratum IV (Early Urban Horizon)",
    depth: 2.1,
    latitude: 20.2963,
    longitude: 85.8248,
    status: "Documented",
    description: "Delicate thinned bowl wall fragment exhibiting the hallmark lustrous mirror-like black slip with silvery sheen. Ferruginous clay with negligible porosity.",
    imageUrl: "https://images.unsplash.com/photo-1618220179428-22790b461013?auto=format&fit=crop&w=800&q=80",
    dateRecorded: "2026-02-28",
    recordedBy: "Dr. A. Sen (Senior Field Archaeologist)"
  },
  {
    id: "ARC-2026-009",
    name: "Gilded Bronze Votive Bell",
    type: "Jewelry",
    material: "Bronze",
    period: "Early Medieval",
    site: "Site B",
    excavationArea: "Southern Terraces - Monastery Quad",
    layer: "Stratum I (Shrine Collapse)",
    depth: 0.6,
    latitude: 20.2902,
    longitude: 85.8298,
    status: "Documented",
    description: "Small ceremonial suspension bell with lotus-petal finial and iron clapper intact. Chemical analysis reveals 82% Cu, 14% Sn, with mercuric fire-gilding traces.",
    imageUrl: "https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80",
    dateRecorded: "2026-03-01",
    recordedBy: "R. Thorne (Metallurgy Team)"
  },
  {
    id: "ARC-2026-010",
    name: "Basalt Grinding Saddle Quern",
    type: "Tool",
    material: "Stone",
    period: "Prehistoric",
    site: "Site C",
    excavationArea: "Eastern Mound - Trench I",
    layer: "Stratum V (Neolithic/Chalcolithic Interface)",
    depth: 3.2,
    latitude: 20.3018,
    longitude: 85.8362,
    status: "Documented",
    description: "Heavily utilized vesicular basalt boat-shaped saddle quern with concave working depression. Microscopic starch granule residues indicate millets and barley processing.",
    imageUrl: "https://images.unsplash.com/photo-1599707367072-cd6ada2bc375?auto=format&fit=crop&w=800&q=80",
    dateRecorded: "2026-03-02",
    recordedBy: "Dr. P. Mohanty (Paleoethnobotany)"
  },
  {
    id: "ARC-2026-011",
    name: "Microlithic Chert Lunate & Bladelet Core",
    type: "Tool",
    material: "Stone",
    period: "Prehistoric",
    site: "Site C",
    excavationArea: "Eastern Mound - Trench II",
    layer: "Stratum VI (Sandy Silt Subsoil)",
    depth: 3.6,
    latitude: 20.3025,
    longitude: 85.8354,
    status: "Documented",
    description: "Fine cryptocrystalline translucent brown chert bladelet core showing bidirectional flake scars, recovered with two abrupt retouched geometric lunates.",
    imageUrl: "https://images.unsplash.com/photo-1533158307587-828f0a76ef46?auto=format&fit=crop&w=800&q=80",
    dateRecorded: "2026-03-03",
    recordedBy: "Dr. P. Mohanty (Paleoethnobotany)"
  },
  {
    id: "ARC-2026-012",
    name: "Chlorite Schist Architectural Plaque",
    type: "Sculpture",
    material: "Stone",
    period: "Medieval",
    site: "Site B",
    excavationArea: "Southern Terraces - Temple Precinct",
    layer: "Stratum II (Debris Mound)",
    depth: 1.2,
    latitude: 20.2898,
    longitude: 85.8305,
    status: "Documented",
    description: "Carved frieze element depicting scrolling vegetal foliage (lata-patra) intertwined with frolicking hamsa waterbirds. Smooth dark greenish-black schist matrix.",
    imageUrl: "https://images.unsplash.com/photo-1549887534-1541e9326642?auto=format&fit=crop&w=800&q=80",
    dateRecorded: "2026-03-04",
    recordedBy: "Dr. K. Rath (Iconography Lead)"
  },
  {
    id: "ARC-2026-013",
    name: "Iron Smelting Crucible & Slag Cake",
    type: "Other",
    material: "Iron",
    period: "Early Medieval",
    site: "Site D",
    excavationArea: "Riverbank Sector - Furnace Bed",
    layer: "Stratum III (Industrial Workshop)",
    depth: 1.9,
    latitude: 20.2852,
    longitude: 85.8182,
    status: "Documented",
    description: "Vitreous refractory ceramic crucible fragment with adherent high-silica iron tap slag. Porous vesicular structure demonstrating bloomery furnace temperatures exceeding 1200°C.",
    imageUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80",
    dateRecorded: "2026-03-05",
    recordedBy: "R. Thorne (Metallurgy Team)"
  },
  {
    id: "ARC-2026-014",
    name: "Forged Iron Adze Head",
    type: "Tool",
    material: "Iron",
    period: "Early Medieval",
    site: "Site D",
    excavationArea: "Riverbank Sector - Workshop 2",
    layer: "Stratum III (Ash Layer)",
    depth: 1.7,
    latitude: 20.2846,
    longitude: 85.8176,
    status: "Documented",
    description: "Heavy carpentry adze featuring curved transverse cutting bit and flared shaft-hole socket. Radiographs demonstrate laminated wrought iron with hardened carburized steel edge.",
    imageUrl: "https://images.unsplash.com/photo-1508873696983-2df5293cb32f?auto=format&fit=crop&w=800&q=80",
    dateRecorded: "2026-03-06",
    recordedBy: "R. Thorne (Metallurgy Team)"
  },
  {
    id: "ARC-2026-015",
    name: "Cast Copper Bangles with Incised Terminals",
    type: "Jewelry",
    material: "Copper",
    period: "Ancient",
    site: "Site B",
    excavationArea: "Southern Terraces - Trench V",
    layer: "Stratum II (Domestic Living Floor)",
    depth: 0.9,
    latitude: 20.2908,
    longitude: 85.8286,
    status: "Documented",
    description: "Pair of penannular copper bracelets with swollen animal-head terminals. Light green malachite encrustation overlying polished core. Inner diameter 58 mm.",
    imageUrl: "https://images.unsplash.com/photo-1611591475152-477d7564d786?auto=format&fit=crop&w=800&q=80",
    dateRecorded: "2026-03-07",
    recordedBy: "Dr. A. Sen (Senior Field Archaeologist)"
  },
  {
    id: "ARC-2026-016",
    name: "Inscribed Copper Plate Grant Fragment",
    type: "Inscription",
    material: "Copper",
    period: "Medieval",
    site: "Site B",
    excavationArea: "Southern Terraces - Temple Vault",
    layer: "Stratum I (Disturbed Upper Silt)",
    depth: 0.5,
    latitude: 20.2894,
    longitude: 85.8312,
    status: "Documented",
    description: "Broken upper-left corner of a charter inscribed in Siddhamatrika script documenting a royal village endowment. Features imperial varaha seal impression.",
    imageUrl: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=800&q=80",
    dateRecorded: "2026-03-08",
    recordedBy: "Prof. H. Sahoo (Epigraphist)"
  },
  {
    id: "ARC-2026-017",
    name: "Moulded Terracotta Elephant Figurine",
    type: "Sculpture",
    material: "Terracotta",
    period: "Ancient",
    site: "Site A",
    excavationArea: "Citadel Sector - Trench IV",
    layer: "Stratum III (Household Shrine Pit)",
    depth: 1.5,
    latitude: 20.2968,
    longitude: 85.8242,
    status: "Documented",
    description: "Hollow double-moulded figurine of a caparisoned elephant with stamped floral blankets (jhula) and coiled trunk. Red slip with post-firing ochre pigment highlights.",
    imageUrl: "https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?auto=format&fit=crop&w=800&q=80",
    dateRecorded: "2026-03-09",
    recordedBy: "Dr. K. Rath (Iconography Lead)"
  },
  {
    id: "ARC-2026-018",
    name: "Perforated Ceramic Steamer Vessel (Colander)",
    type: "Pottery",
    material: "Clay",
    period: "Ancient",
    site: "Site A",
    excavationArea: "Citadel Sector - Trench VI",
    layer: "Stratum II (Kitchen Hearth Complex)",
    depth: 1.0,
    latitude: 20.2955,
    longitude: 85.8250,
    status: "Documented",
    description: "Coarse grey-ware shallow hemispherical basin with uniformly spaced 4 mm perforations across base. Extensive exterior soot crust confirming culinary thermal use.",
    imageUrl: "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=800&q=80",
    dateRecorded: "2026-03-10",
    recordedBy: "Dr. A. Sen (Senior Field Archaeologist)"
  },
  {
    id: "ARC-2026-019",
    name: "Gold Dinara Coin (Kushan Imitation)",
    type: "Coin",
    material: "Other",
    period: "Ancient",
    site: "Site E",
    excavationArea: "Outer Enclosure - Gatehouse Bastion",
    layer: "Stratum II (Paved Gate Threshold)",
    depth: 0.8,
    latitude: 20.3078,
    longitude: 85.8208,
    status: "Documented",
    description: "High-grade gold coin (7.98 g) depicting king standing sacrificing at fire altar on obverse; reverse features enthroned goddess Ardoxsho with cornucopia and monogram.",
    imageUrl: "https://images.unsplash.com/photo-1610375461246-83df859d849d?auto=format&fit=crop&w=800&q=80",
    dateRecorded: "2026-03-11",
    recordedBy: "M. Vance (Numismatics Specialist)"
  },
  {
    id: "ARC-2026-020",
    name: "Glazed Islamic Monochrome Sherd",
    type: "Pottery",
    material: "Clay",
    period: "Late Medieval",
    site: "Site E",
    excavationArea: "Outer Enclosure - Surface Scraping",
    layer: "Stratum I (Topsoil Humus)",
    depth: 0.3,
    latitude: 20.3085,
    longitude: 85.8215,
    status: "Documented",
    description: "Quartz-frit paste body bearing brilliant turquoise alkaline glaze with fine micro-crazing. Probable trade ware sherd linked to regional maritime trade routes.",
    imageUrl: "https://images.unsplash.com/photo-1579762715118-a6f1d4b934f1?auto=format&fit=crop&w=800&q=80",
    dateRecorded: "2026-03-12",
    recordedBy: "Dr. A. Sen (Senior Field Archaeologist)"
  },
  {
    id: "ARC-2026-021",
    name: "Decorated Terracotta Well Ring Segment",
    type: "Brick",
    material: "Terracotta",
    period: "Ancient",
    site: "Site D",
    excavationArea: "Riverbank Sector - Ring Well 3",
    layer: "Stratum IV (Alluvial Flood Silt)",
    depth: 2.7,
    latitude: 20.2858,
    longitude: 85.8188,
    status: "Documented",
    description: "Heavy curved ceramic cylinder ring from a soakage pit/pottery well stack. Features pronounced exterior finger grooves to prevent silt slippage during excavation.",
    imageUrl: "https://images.unsplash.com/photo-1590069261209-f8e9b8642343?auto=format&fit=crop&w=800&q=80",
    dateRecorded: "2026-03-13",
    recordedBy: "T. Bennett (Survey Architect)"
  },
  {
    id: "ARC-2026-022",
    name: "Cast Lead Ingot Bar with Merchant Stamp",
    type: "Other",
    material: "Other",
    period: "Ancient",
    site: "Site D",
    excavationArea: "Riverbank Sector - Wharf Edge",
    layer: "Stratum III (River Landing Floor)",
    depth: 1.5,
    latitude: 20.2842,
    longitude: 85.8170,
    status: "Documented",
    description: "Trapezoidal plano-convex lead bar ingot weighing 1.42 kg. Deeply impressed rectangular stamp bearing triratna symbol and guild mark. Essential for brass and coin minting.",
    imageUrl: "https://images.unsplash.com/photo-1533158307587-828f0a76ef46?auto=format&fit=crop&w=800&q=80",
    dateRecorded: "2026-03-14",
    recordedBy: "R. Thorne (Metallurgy Team)"
  },
  {
    id: "ARC-2026-023",
    name: "Steatite Stamp Seal with Unicorn Motif",
    type: "Inscription",
    material: "Stone",
    period: "Prehistoric",
    site: "Site C",
    excavationArea: "Eastern Mound - Trench IV",
    layer: "Stratum V (Late Harappan Affiliated Level)",
    depth: 3.4,
    latitude: 20.3012,
    longitude: 85.8368,
    status: "Documented",
    description: "Square white vitrified steatite seal with pierced boss on back. Deep intaglio carving of standing mythical beast before offering stand, topped by six linear ideograms.",
    imageUrl: "https://images.unsplash.com/photo-1569683795645-b62e50fbf103?auto=format&fit=crop&w=800&q=80",
    dateRecorded: "2026-03-15",
    recordedBy: "Prof. H. Sahoo (Epigraphist)"
  },
  {
    id: "ARC-2026-024",
    name: "Red Slipped Ware Spouted Jar Neck",
    type: "Pottery",
    material: "Terracotta",
    period: "Ancient",
    site: "Site A",
    excavationArea: "Citadel Sector - Trench I",
    layer: "Stratum III (Residential Rubble)",
    depth: 1.3,
    latitude: 20.2967,
    longitude: 85.8238,
    status: "Documented",
    description: "Finely burnished lustrous red slip bottle neck with an intact tubular animal-head spout. Clay matrix well-levigated with negligible coarse inclusions.",
    imageUrl: "https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=800&q=80",
    dateRecorded: "2026-03-16",
    recordedBy: "Dr. A. Sen (Senior Field Archaeologist)"
  },
  {
    id: "ARC-2026-025",
    name: "East India Company Bronze Half Anna",
    type: "Coin",
    material: "Bronze",
    period: "Colonial",
    site: "Site E",
    excavationArea: "Outer Enclosure - Surface Trench",
    layer: "Stratum I (Agricultural Overburden)",
    depth: 0.2,
    latitude: 20.3072,
    longitude: 85.8220,
    status: "Documented",
    description: "Circular copper/bronze coin dated 1835 bearing arms of the East India Company on obverse and denomination wreath in English/Persian on reverse.",
    imageUrl: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=800&q=80",
    dateRecorded: "2026-03-17",
    recordedBy: "M. Vance (Numismatics Specialist)"
  },
  {
    id: "ARC-2026-026",
    name: "Polished Granite Neolithic Celt / Hand Axe",
    type: "Tool",
    material: "Stone",
    period: "Prehistoric",
    site: "Site C",
    excavationArea: "Eastern Mound - Trench III",
    layer: "Stratum V (Basal Gravel Terrace)",
    depth: 3.1,
    latitude: 20.3008,
    longitude: 85.8351,
    status: "Documented",
    description: "Trapezoidal dark speckled granite celt with finely ground and polished cutting edge. Butt end shows light pecking for hafting onto a wooden elbow shaft.",
    imageUrl: "https://images.unsplash.com/photo-1599707367072-cd6ada2bc375?auto=format&fit=crop&w=800&q=80",
    dateRecorded: "2026-03-18",
    recordedBy: "Dr. P. Mohanty (Paleoethnobotany)"
  },
  {
    id: "ARC-2026-027",
    name: "Carved Ivory Dice with Punctated Dots",
    type: "Other",
    material: "Other",
    period: "Ancient",
    site: "Site A",
    excavationArea: "Citadel Sector - Trench III",
    layer: "Stratum II (Palatial Gaming Room)",
    depth: 0.7,
    latitude: 20.2972,
    longitude: 85.8247,
    status: "Documented",
    description: "Long rectangular four-sided gaming rod carved from elephant ivory. Numbered 1 to 4 with concentric ring punctations filled with black bitumen ink.",
    imageUrl: "https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80",
    dateRecorded: "2026-03-19",
    recordedBy: "Dr. A. Sen (Senior Field Archaeologist)"
  },
  {
    id: "ARC-2026-028",
    name: "Iron Riveted Gate Hasp & Hinge",
    type: "Tool",
    material: "Iron",
    period: "Medieval",
    site: "Site E",
    excavationArea: "Outer Enclosure - South Bastion",
    layer: "Stratum II (Fort Gate Destruction Horizon)",
    depth: 1.1,
    latitude: 20.3088,
    longitude: 85.8202,
    status: "Documented",
    description: "Heavy forged iron gate bracket with three hand-peened dome-head rivets surviving. Massive structural fitting confirming heavy fortified timber leaves.",
    imageUrl: "https://images.unsplash.com/photo-1508873696983-2df5293cb32f?auto=format&fit=crop&w=800&q=80",
    dateRecorded: "2026-03-20",
    recordedBy: "R. Thorne (Metallurgy Team)"
  },
  {
    id: "ARC-2026-029",
    name: "Moulded Architectural Terracotta Tile with Lotus Rosette",
    type: "Brick",
    material: "Terracotta",
    period: "Ancient",
    site: "Site B",
    excavationArea: "Southern Terraces - Trench IV",
    layer: "Stratum III (Colonnade Collapse)",
    depth: 1.6,
    latitude: 20.2915,
    longitude: 85.8294,
    status: "Documented",
    description: "Square interlocking roof/flooring tile decorated with a bold high-relief eight-petalled lotus roundel within a pearl border. Deep keying grooves on underside.",
    imageUrl: "https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?auto=format&fit=crop&w=800&q=80",
    dateRecorded: "2026-03-21",
    recordedBy: "T. Bennett (Survey Architect)"
  },
  {
    id: "ARC-2026-030",
    name: "Black-and-Red Ware (BRW) Deep Carinated Bowl",
    type: "Pottery",
    material: "Clay",
    period: "Ancient",
    site: "Site C",
    excavationArea: "Eastern Mound - Trench I",
    layer: "Stratum IV (Iron Age Settlement Layer)",
    depth: 2.8,
    latitude: 20.3021,
    longitude: 85.8359,
    status: "Documented",
    description: "Classic inverted-firing Black-and-Red Ware bowl with lustrous black interior and red exterior margin. Sharply carinated waist with thin uncorrugated rim.",
    imageUrl: "https://images.unsplash.com/photo-1618220179428-22790b461013?auto=format&fit=crop&w=800&q=80",
    dateRecorded: "2026-03-22",
    recordedBy: "Dr. A. Sen (Senior Field Archaeologist)"
  },
  {
    id: "ARC-2026-031",
    name: "Cast Copper Miniature Bull Figurine",
    type: "Sculpture",
    material: "Copper",
    period: "Ancient",
    site: "Site A",
    excavationArea: "Citadel Sector - Trench V",
    layer: "Stratum III (Ritual Offering Pit)",
    depth: 1.4,
    latitude: 20.2960,
    longitude: 85.8258,
    status: "Documented",
    description: "Solid lost-wax cast humped zebu bull figurine with forward-curving horns, dewlap folds, and garland garland incisions across shoulder.",
    imageUrl: "https://images.unsplash.com/photo-1544967082-d9d25d867d66?auto=format&fit=crop&w=800&q=80",
    dateRecorded: "2026-03-23",
    recordedBy: "Dr. K. Rath (Iconography Lead)"
  },
  {
    id: "ARC-2026-032",
    name: "Roman Amphora Handle Sherd (Dressel 2-4)",
    type: "Pottery",
    material: "Clay",
    period: "Ancient",
    site: "Site D",
    excavationArea: "Riverbank Sector - Port Embankment",
    layer: "Stratum III (Maritime Customs Dump)",
    depth: 1.8,
    latitude: 20.2855,
    longitude: 85.8174,
    status: "Documented",
    description: "Bifid double-rod wine amphora handle fragment in pinkish-buff Campanian fabric with volcanic pyroxene inclusions. Direct physical evidence of Indo-Roman spice trade.",
    imageUrl: "https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=800&q=80",
    dateRecorded: "2026-03-24",
    recordedBy: "Dr. A. Sen (Senior Field Archaeologist)"
  },
  {
    id: "ARC-2026-033",
    name: "Faience Biconical Spindle Whorl",
    type: "Tool",
    material: "Other",
    period: "Prehistoric",
    site: "Site C",
    excavationArea: "Eastern Mound - Trench II",
    layer: "Stratum V (Weaving Quarters)",
    depth: 2.9,
    latitude: 20.3016,
    longitude: 85.8364,
    status: "Documented",
    description: "Vitreous glassy turquoise faience whorl showing radial incised petal grooves and circular central spindle hole with rotary wear gloss.",
    imageUrl: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=800&q=80",
    dateRecorded: "2026-03-25",
    recordedBy: "Dr. P. Mohanty (Paleoethnobotany)"
  },
  {
    id: "ARC-2026-034",
    name: "Mutilated Schist Ganesha Pedestal",
    type: "Sculpture",
    material: "Stone",
    period: "Early Medieval",
    site: "Site B",
    excavationArea: "Southern Terraces - Niche 4",
    layer: "Stratum II (Demolition Layer)",
    depth: 1.3,
    latitude: 20.2900,
    longitude: 85.8288,
    status: "Documented",
    description: "Pedestal fragment carved with the mouse vahana looking up toward foot residues. Chlorite schist with remnant ritual vermillion oil crust.",
    imageUrl: "https://images.unsplash.com/photo-1549887534-1541e9326642?auto=format&fit=crop&w=800&q=80",
    dateRecorded: "2026-03-26",
    recordedBy: "Dr. K. Rath (Iconography Lead)"
  },
  {
    id: "ARC-2026-035",
    name: "Isolated Quartzite Flake (Peripheral Noise Point)",
    type: "Tool",
    material: "Stone",
    period: "Prehistoric",
    site: "Site C",
    excavationArea: "Outlying Survey Transect Delta",
    layer: "Surface Scree",
    depth: 0.1,
    latitude: 20.2780,
    longitude: 85.8450,
    status: "Documented",
    description: "Single unretouched quartzite levallois flake located 2.4 km southeast of primary cluster. Prominent bulb of percussion and dorsal flake negative.",
    imageUrl: "https://images.unsplash.com/photo-1533158307587-828f0a76ef46?auto=format&fit=crop&w=800&q=80",
    dateRecorded: "2026-03-27",
    recordedBy: "Dr. P. Mohanty (Paleoethnobotany)"
  },
  {
    id: "ARC-2026-036",
    name: "Isolated Iron Nail Fragment (Peripheral Noise Point)",
    type: "Tool",
    material: "Iron",
    period: "Colonial",
    site: "Site E",
    excavationArea: "Northern Survey Boundary Transect",
    layer: "Topsoil Scrub",
    depth: 0.15,
    latitude: 20.3150,
    longitude: 85.8100,
    status: "Documented",
    description: "Square-shank hand-wrought iron spikes recovered from ploughzone at extreme northern survey grid boundary. Isolated observation outside core clusters.",
    imageUrl: "https://images.unsplash.com/photo-1508873696983-2df5293cb32f?auto=format&fit=crop&w=800&q=80",
    dateRecorded: "2026-03-28",
    recordedBy: "T. Bennett (Survey Architect)"
  }
];

// Color mapping for Artifact Types across GIS, Charts, and Badges
const TYPE_CONFIG = {
  Pottery: { color: "#C85A32", bg: "rgba(200, 90, 50, 0.18)", text: "#F39C72", icon: "fa-wine-bottle", label: "Pottery" },
  Coin: { color: "#D4AF37", bg: "rgba(212, 175, 55, 0.18)", text: "#FAD02C", icon: "fa-coins", label: "Coins" },
  Sculpture: { color: "#8E44AD", bg: "rgba(142, 68, 173, 0.18)", text: "#BB8FCE", icon: "fa-monument", label: "Sculptures" },
  Tool: { color: "#2980B9", bg: "rgba(41, 128, 185, 0.18)", text: "#5DADE2", icon: "fa-hammer", label: "Tools" },
  Jewelry: { color: "#E84393", bg: "rgba(232, 67, 147, 0.18)", text: "#F1948A", icon: "fa-gem", label: "Jewelry" },
  Inscription: { color: "#27AE60", bg: "rgba(39, 174, 96, 0.18)", text: "#58D68D", icon: "fa-scroll", label: "Inscriptions" },
  Brick: { color: "#E67E22", bg: "rgba(230, 126, 34, 0.18)", text: "#F5B041", icon: "fa-cubes", label: "Bricks" },
  Other: { color: "#7F8C8D", bg: "rgba(127, 140, 141, 0.18)", text: "#BDC3C7", icon: "fa-layer-group", label: "Other" }
};

const MATERIAL_CONFIG = {
  Terracotta: { color: "#D36B46" },
  Stone: { color: "#8C7B6C" },
  Clay: { color: "#B38F6B" },
  Bronze: { color: "#CD7F32" },
  Iron: { color: "#5D6D7E" },
  Copper: { color: "#B87333" },
  Other: { color: "#AAB7B8" }
};

const PERIOD_CONFIG = {
  Prehistoric: { color: "#8E44AD" },
  Ancient: { color: "#C85A32" },
  "Early Medieval": { color: "#D4AF37" },
  Medieval: { color: "#2980B9" },
  "Late Medieval": { color: "#16A085" },
  Colonial: { color: "#E74C3C" },
  Modern: { color: "#95A5A6" },
  Unknown: { color: "#7F8C8D" }
};

const SITE_CONFIG = {
  "Site A": { name: "Citadel Sector", center: [20.2961, 85.8245], count: 11, desc: "Primary fortified urban acropolis and palatial residential mounds" },
  "Site B": { name: "Southern Terraces", center: [20.2905, 85.8290], count: 8, desc: "Religious monastery complex, temple platforms, and elite funerary zones" },
  "Site C": { name: "Eastern Mound", center: [20.3015, 85.8360], count: 7, desc: "Multi-period prehistoric chalcolithic terrace and craft workshops" },
  "Site D": { name: "Riverbank Sector", center: [20.2850, 85.8180], count: 5, desc: "Ancient river port, metallurgical bloomeries, and alluvial ring wells" },
  "Site E": { name: "Outer Enclosure", center: [20.3080, 85.8210], count: 5, desc: "Peripheral defensive curtain wall bastions, monumental gateway, and surface transects" }
};
