/**
 * ARCHAEO-BHĀRAT - Curated Indian Archaeological Survey Dataset
 * Authentic field discoveries across 6 iconic civilization sectors:
 * 1. Dholavira & Lothal (Indus Valley / Harappan Bronze Age - Gujarat)
 * 2. Sisupalgarh & Dhauli (Ancient Kalinga Citadel & Ashokan Edicts - Odisha)
 * 3. Sanchi & Vidisha (Mauryan Stupa Complex - Madhya Pradesh)
 * 4. Nalanda Mahavihara (Ancient Buddhist University - Bihar)
 * 5. Hampi / Vijayanagara (Imperial Capital - Karnataka)
 * 6. Keezhadi (Sangam Era Vaigai Valley Horizon - Tamil Nadu)
 */

const INITIAL_ARTIFACTS = [
  // --- DHOLAVIRA & LOTHAL (INDUS VALLEY / HARAPPAN) ---
  {
    id: "IND-2026-001",
    name: "Steatite Unicorn Stamp Seal with Indus Script",
    type: "Inscription",
    material: "Stone",
    period: "Harappan (Indus Valley)",
    site: "Dholavira",
    excavationArea: "Citadel (Bailey) - Gate 4",
    layer: "Stratum V (Mature Harappan Urban Level)",
    depth: 3.2,
    latitude: 23.8864,
    longitude: 70.2135,
    status: "Documented",
    description: "Square vitrified white steatite stamp seal featuring a deep intaglio carving of a mythical unicorn standing before an offering standard. Five Indus script signs engraved along upper margin. Pierced perforated boss on reverse.",
    imageUrl: "https://images.unsplash.com/photo-1569683795645-b62e50fbf103?auto=format&fit=crop&w=800&q=80",
    dateRecorded: "2026-01-15",
    recordedBy: "Dr. R. S. Bisht (Harappan Epigraphy Lead)"
  },
  {
    id: "IND-2026-002",
    name: "Terracotta Marine Dockyard Cargo Boat Model",
    type: "Sculpture",
    material: "Terracotta",
    period: "Harappan (Indus Valley)",
    site: "Dholavira",
    excavationArea: "East Water Reservoir / Bund",
    layer: "Stratum IV (Alluvial Basin Mud)",
    depth: 2.8,
    latitude: 23.8858,
    longitude: 70.2148,
    status: "Documented",
    description: "Hand-modelled hollow terracotta model of a high-prowed seafaring vessel with central mast socket. Remnant dark brown slip showing geometric hull lashings. Correlates with Gulf of Khambhat maritime trading networks.",
    imageUrl: "https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=800&q=80",
    dateRecorded: "2026-01-18",
    recordedBy: "Dr. A. Sharma (Maritime Archaeology Lead)"
  },
  {
    id: "IND-2026-003",
    name: "Etched Carnelian & Banded Agate Beads",
    type: "Jewelry",
    material: "Stone",
    period: "Harappan (Indus Valley)",
    site: "Dholavira",
    excavationArea: "Middle Town - Bead Workshop IV",
    layer: "Stratum IV (Lapidary Floor Level)",
    depth: 2.4,
    latitude: 23.8872,
    longitude: 70.2120,
    status: "Documented",
    description: "Nine barrel and biconical carnelian beads decorated with white alkali etched concentric circles and chevrons. Diamond micro-drill cylindrical borings intact.",
    imageUrl: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=800&q=80",
    dateRecorded: "2026-01-22",
    recordedBy: "P. Patel (Lapidary Specialist)"
  },
  {
    id: "IND-2026-004",
    name: "Chert Cubical Precision Weight Set",
    type: "Tool",
    material: "Stone",
    period: "Harappan (Indus Valley)",
    site: "Dholavira",
    excavationArea: "Citadel - Customs Gate",
    layer: "Stratum V (Administrative Horizon)",
    depth: 3.0,
    latitude: 23.8860,
    longitude: 70.2130,
    status: "Documented",
    description: "Highly polished cubical balance weights cut from dense grey-banded Rohri chert. Mass adheres strictly to the binary Indus standard (1, 2, 4, 8, 16 ratio = 13.63 g unit base).",
    imageUrl: "https://images.unsplash.com/photo-1599707367072-cd6ada2bc375?auto=format&fit=crop&w=800&q=80",
    dateRecorded: "2026-01-25",
    recordedBy: "Dr. R. S. Bisht (Harappan Epigraphy Lead)"
  },

  // --- SISUPALGARH & DHAULI (KALINGA & ASHOKAN) ---
  {
    id: "IND-2026-005",
    name: "Ashokan Brahmi Rock Edict Fragment",
    type: "Inscription",
    material: "Stone",
    period: "Mauryan (c. 250 BCE)",
    site: "Sisupalgarh",
    excavationArea: "Western Gateway Bastion Trench II",
    layer: "Stratum IV (Ashokan Monumental Revetment)",
    depth: 2.2,
    latitude: 20.2968,
    longitude: 85.8248,
    status: "Documented",
    description: "Fine-grained Khandolite sandstone slab fragment preserving two lines of deep lapidary early Ashokan Brahmi reading '...devānaṁpiyena piyadasinā lājinā...' with dharma wheel emblem.",
    imageUrl: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=800&q=80",
    dateRecorded: "2026-02-02",
    recordedBy: "Prof. H. C. Sahoo (Senior Epigraphist, ASI)"
  },
  {
    id: "IND-2026-006",
    name: "Punch-Marked Silver Karshapana (Puranas)",
    type: "Coin",
    material: "Copper",
    period: "Mauryan (c. 300 BCE)",
    site: "Sisupalgarh",
    excavationArea: "Citadel Sector - Trench I",
    layer: "Stratum III (Late Mauryan Living Floor)",
    depth: 1.4,
    latitude: 20.2961,
    longitude: 85.8245,
    status: "Documented",
    description: "Rectangular-clipped silver-copper billon coin displaying five distinct punches: solar rayed symbol, six-armed wheel (shadarachakra), arched hill with crescent, elephant, and taurine.",
    imageUrl: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=800&q=80",
    dateRecorded: "2026-02-05",
    recordedBy: "Dr. B. K. Thapar (Numismatics)"
  },
  {
    id: "IND-2026-007",
    name: "Northern Black Polished Ware (NBPW) Deluxe Bowl",
    type: "Pottery",
    material: "Clay",
    period: "Mauryan (c. 300 BCE)",
    site: "Sisupalgarh",
    excavationArea: "Citadel Trench IV",
    layer: "Stratum IV (Early Urban Habitation)",
    depth: 2.1,
    latitude: 20.2974,
    longitude: 85.8256,
    status: "Documented",
    description: "Superbly levigated, extremely thin-walled bowl fragment boasting the celebrated mirror-like lustrous coal-black slip with silvery metallic sheen. Characteristic of elite Mauryan urban horizons.",
    imageUrl: "https://images.unsplash.com/photo-1618220179428-22790b461013?auto=format&fit=crop&w=800&q=80",
    dateRecorded: "2026-02-10",
    recordedBy: "Dr. A. Sen (Senior Field Archaeologist)"
  },
  {
    id: "IND-2026-008",
    name: "Moulded Terracotta Plaque with Caparisoned Elephant",
    type: "Sculpture",
    material: "Terracotta",
    period: "Shunga-Andhra (c. 150 BCE)",
    site: "Sisupalgarh",
    excavationArea: "Southern Rampart Gate",
    layer: "Stratum III (Colonnade Floor)",
    depth: 1.6,
    latitude: 20.2958,
    longitude: 85.8240,
    status: "Documented",
    description: "High-relief terracotta plaque showing an ornate royal elephant with stamped floral blankets (jhula), bell trappings, and seated royal driver (mahout) holding an ankusha.",
    imageUrl: "https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?auto=format&fit=crop&w=800&q=80",
    dateRecorded: "2026-02-14",
    recordedBy: "Dr. K. Rath (Iconography Lead)"
  },

  // --- SANCHI & VIDISHA (MAURYAN & SHUNGA) ---
  {
    id: "IND-2026-009",
    name: "Red Sandstone Salabhanjika Bracket Fragment",
    type: "Sculpture",
    material: "Stone",
    period: "Shunga-Satavahana (c. 100 BCE)",
    site: "Sanchi",
    excavationArea: "Great Stupa - North Torana Area",
    layer: "Stratum III (Temple Platform Rubble)",
    depth: 1.5,
    latitude: 23.4796,
    longitude: 77.7398,
    status: "Documented",
    description: "Spotted red Vindhyan sandstone torana bracket carving of a celestial tree-nymph (Salabhanjika) in flowing tribhanga posture clutching a blooming mango bough. Exquisite micro-chiseled jewelry folds.",
    imageUrl: "https://images.unsplash.com/photo-1544967082-d9d25d867d66?auto=format&fit=crop&w=800&q=80",
    dateRecorded: "2026-02-20",
    recordedBy: "Sir John Marshall Archive / Dr. V. Trivedi"
  },
  {
    id: "IND-2026-010",
    name: "Gilded Bronze Votive Dharma Stupa Reliquary",
    type: "Jewelry",
    material: "Bronze",
    period: "Gupta Classical (c. 450 CE)",
    site: "Sanchi",
    excavationArea: "Monastery 51 - Relic Chamber",
    layer: "Stratum II (Monastic Votive Vault)",
    depth: 0.9,
    latitude: 23.4802,
    longitude: 77.7410,
    status: "Documented",
    description: "Miniature cast bronze hemispherical stupa reliquary surmounted by a harmika and three-tiered chhatra umbrella. Gilded in gold amalgam; interior contained crystal micro-beads and charred jasmine remnants.",
    imageUrl: "https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80",
    dateRecorded: "2026-02-24",
    recordedBy: "Dr. V. Trivedi (Buddhist Studies Lead)"
  },
  {
    id: "IND-2026-011",
    name: "Carved Stone Ashokan Dharmachakra Hub",
    type: "Sculpture",
    material: "Stone",
    period: "Mauryan (c. 250 BCE)",
    site: "Sanchi",
    excavationArea: "Pillar 25 Sub-structure",
    layer: "Stratum IV (Mauryan Monolithic Foundation)",
    depth: 2.3,
    latitude: 23.4792,
    longitude: 77.7392,
    status: "Documented",
    description: "Chunar sandstone hub of a 32-spoked ceremonial Dharmachakra with characteristic mirror-glass Mauryan lustrous polish. Surmounted originally on the monumental pillar capital.",
    imageUrl: "https://images.unsplash.com/photo-1549887534-1541e9326642?auto=format&fit=crop&w=800&q=80",
    dateRecorded: "2026-02-28",
    recordedBy: "Prof. H. C. Sahoo (Senior Epigraphist, ASI)"
  },

  // --- NALANDA MAHAVIHARA (ANCIENT MONASTIC UNIVERSITY) ---
  {
    id: "IND-2026-012",
    name: "Official Nalanda Mahavihara Clay Monastic Bulla",
    type: "Inscription",
    material: "Clay",
    period: "Gupta-Pala (c. 700 CE)",
    site: "Nalanda",
    excavationArea: "Monastery Site 1 - Administrative Cell",
    layer: "Stratum II (Library Silt Deposit)",
    depth: 1.1,
    latitude: 25.1358,
    longitude: 85.4455,
    status: "Documented",
    description: "Circular terracotta institutional bulla seal showing the seated Dharmachakra flanked by two kneeling deer. Legend in late Brahmi reads: 'Śrī-Nālandā-mahāvihāriy-ārya-bhikṣu-saṅghasya' (Of the Venerable Monastic Assembly of Nalanda).",
    imageUrl: "https://images.unsplash.com/photo-1569683795645-b62e50fbf103?auto=format&fit=crop&w=800&q=80",
    dateRecorded: "2026-03-02",
    recordedBy: "Dr. S. K. Mitra (Pala Epigraphy Specialist)"
  },
  {
    id: "IND-2026-013",
    name: "Lost-Wax Cast Bronze Avalokiteshvara Figurine",
    type: "Sculpture",
    material: "Bronze",
    period: "Pala Period (c. 850 CE)",
    site: "Nalanda",
    excavationArea: "Temple Site 3 - Chaitya Niche",
    layer: "Stratum II (Shrine Debris)",
    depth: 1.3,
    latitude: 25.1365,
    longitude: 85.4462,
    status: "Documented",
    description: "Solid ashtadhatu bronze icon of Avalokiteshvara Padmapani standing upon a lotus pedestal, holding a lotus stalk with right hand in varada mudra. Inlaid silver eye pupils intact.",
    imageUrl: "https://images.unsplash.com/photo-1595769816263-9b910be24d5f?auto=format&fit=crop&w=800&q=80",
    dateRecorded: "2026-03-05",
    recordedBy: "R. Thorne (Metallurgy Team)"
  },
  {
    id: "IND-2026-014",
    name: "Gold Dinar of Chandragupta II (Archer Type)",
    type: "Coin",
    material: "Other",
    period: "Gupta Classical (c. 400 CE)",
    site: "Nalanda",
    excavationArea: "Monastery Quadrangle Site 4",
    layer: "Stratum III (Gupta Vault Level)",
    depth: 1.7,
    latitude: 25.1352,
    longitude: 85.4448,
    status: "Documented",
    description: "High-grade pure gold dinara (8.15 g). Obverse: King standing left holding bow and arrow, with Garuda standard behind; Brahmi legend 'Deva Sri Maharajadhiraja Sri Chandraguptah'. Reverse: Goddess Lakshmi seated upon lotus.",
    imageUrl: "https://images.unsplash.com/photo-1610375461246-83df859d849d?auto=format&fit=crop&w=800&q=80",
    dateRecorded: "2026-03-08",
    recordedBy: "Dr. B. K. Thapar (Numismatics)"
  },

  // --- HAMPI / VIJAYANAGARA (IMPERIAL CAPITAL) ---
  {
    id: "IND-2026-015",
    name: "Gold Gadyana Pagoda (Bala Krishna Type)",
    type: "Coin",
    material: "Other",
    period: "Vijayanagara (c. 1515 CE)",
    site: "Hampi",
    excavationArea: "Krishna Temple Sacred Bazaar",
    layer: "Stratum I (Paved Market Corridor)",
    depth: 0.5,
    latitude: 15.3352,
    longitude: 76.4608,
    status: "Documented",
    description: "Gold Varaha pagoda issued under Emperor Krishnadevaraya. Obverse displays infant Krishna crawling with butter ball in right hand. Reverse bears three-line Devanagari legend reading 'Sri Pratapa Krishna Raya'.",
    imageUrl: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=800&q=80",
    dateRecorded: "2026-03-11",
    recordedBy: "M. Vance (Numismatics Specialist)"
  },
  {
    id: "IND-2026-016",
    name: "Carved Chlorite Stone Frieze with Royal Procession",
    type: "Sculpture",
    material: "Stone",
    period: "Vijayanagara (c. 1500 CE)",
    site: "Hampi",
    excavationArea: "Mahanavami Dibba Terrace III",
    layer: "Stratum II (Imperial Court Platform)",
    depth: 0.9,
    latitude: 15.3360,
    longitude: 76.4620,
    status: "Documented",
    description: "Deep relief architectural frieze depicting royal elephant riders, Central Asian foreign horse traders, and kolata stick dancers in spirited movement. Polished dark chlorite schist.",
    imageUrl: "https://images.unsplash.com/photo-1549887534-1541e9326642?auto=format&fit=crop&w=800&q=80",
    dateRecorded: "2026-03-14",
    recordedBy: "Dr. K. Rath (Iconography Lead)"
  },
  {
    id: "IND-2026-017",
    name: "Forged Iron Battleaxe & Fortification Cannonballs",
    type: "Tool",
    material: "Iron",
    period: "Vijayanagara (c. 1565 CE)",
    site: "Hampi",
    excavationArea: "Zenana Enclosure - Guard Quarters",
    layer: "Stratum II (Siege Destruction Layer)",
    depth: 1.2,
    latitude: 15.3345,
    longitude: 76.4595,
    status: "Documented",
    description: "Heavy carbonized iron pole-axe with reinforcing brass collars, recovered alongside six cast-iron cannonballs from the Battle of Talikota horizon.",
    imageUrl: "https://images.unsplash.com/photo-1508873696983-2df5293cb32f?auto=format&fit=crop&w=800&q=80",
    dateRecorded: "2026-03-17",
    recordedBy: "R. Thorne (Metallurgy Team)"
  },

  // --- KEEZHADI (SANGAM VAIGAI VALLEY CIVILIZATION) ---
  {
    id: "IND-2026-018",
    name: "Tamil-Brahmi Inscribed Black-and-Red Ware Sherd",
    type: "Inscription",
    material: "Clay",
    period: "Sangam Era (c. 500 BCE)",
    site: "Keezhadi",
    excavationArea: "Locality IV - Weaver Household Trench",
    layer: "Stratum III (Vaigai Flood Silt)",
    depth: 1.8,
    latitude: 9.8625,
    longitude: 78.1885,
    status: "Documented",
    description: "Shoulder sherd of a carinated urn bowl bearing post-firing graffito in archaic Tamil-Brahmi (Damili) script reading personal name 'Āthan'. Confirms urban literacy in deep South India by 6th century BCE.",
    imageUrl: "https://images.unsplash.com/photo-1618220179428-22790b461013?auto=format&fit=crop&w=800&q=80",
    dateRecorded: "2026-03-20",
    recordedBy: "Dr. K. Amarnath Ramakrishna (Excavation Director, ASI)"
  },
  {
    id: "IND-2026-019",
    name: "Carved Ivory Dice with Punctated Concentric Circles",
    type: "Other",
    material: "Other",
    period: "Sangam Era (c. 400 BCE)",
    site: "Keezhadi",
    excavationArea: "Trench XII - Aristocratic Quarter",
    layer: "Stratum III (Living Floor 2)",
    depth: 1.6,
    latitude: 9.8631,
    longitude: 78.1892,
    status: "Documented",
    description: "Four-sided rectangular ivory gaming rod polished to high sheen. Markings 1, 2, 3, 4 indicated by circular ring-and-dot drill punctations filled with carbon pigment.",
    imageUrl: "https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80",
    dateRecorded: "2026-03-23",
    recordedBy: "Dr. K. Amarnath Ramakrishna (Excavation Director, ASI)"
  },
  {
    id: "IND-2026-020",
    name: "Spindle Whorl & Terracotta Dyeing Vat Rim",
    type: "Tool",
    material: "Terracotta",
    period: "Sangam Era (c. 400 BCE)",
    site: "Keezhadi",
    excavationArea: "Trench IX - Textile Processing Yard",
    layer: "Stratum IV (Industrial Floor)",
    depth: 2.1,
    latitude: 9.8618,
    longitude: 78.1878,
    status: "Documented",
    description: "Terracotta grooved spindle whorl for fine cotton muslin yarn spinning, recovered adjacent to burnt brick floor drain and dyeing vats mentioned in Sangam poetry.",
    imageUrl: "https://images.unsplash.com/photo-1590069261209-f8e9b8642343?auto=format&fit=crop&w=800&q=80",
    dateRecorded: "2026-03-26",
    recordedBy: "Dr. P. Mohanty (Paleoethnobotany)"
  },

  // --- ADDITIONAL RICH SITES ACROSS BHĀRAT ---
  {
    id: "IND-2026-021",
    name: "Chola Lost-Wax Bronze Nataraja Torso Fragment",
    type: "Sculpture",
    material: "Bronze",
    period: "Chola Imperial (c. 1050 CE)",
    site: "Keezhadi",
    excavationArea: "Temple Outskirts Trench",
    layer: "Stratum II (Medieval Collapse)",
    depth: 1.0,
    latitude: 9.8638,
    longitude: 78.1901,
    status: "Documented",
    description: "Magnificent solid bronze casting fragment of Shiva Nataraja's dancing upper torso with sacred thread (yajnopavita) and billowing matted dreadlocks bearing Ganga and crescent moon.",
    imageUrl: "https://images.unsplash.com/photo-1544967082-d9d25d867d66?auto=format&fit=crop&w=800&q=80",
    dateRecorded: "2026-03-28",
    recordedBy: "Dr. K. Rath (Iconography Lead)"
  },
  {
    id: "IND-2026-022",
    name: "Copper-Hoard Anthropomorphic Cult Figurine",
    type: "Tool",
    material: "Copper",
    period: "Vedic / OCP Horizon (c. 1500 BCE)",
    site: "Sanchi",
    excavationArea: "Betwa Riverbank Survey Transect",
    layer: "Stratum V (Pre-Mauryan Gravel Horizon)",
    depth: 2.9,
    latitude: 23.4785,
    longitude: 77.7380,
    status: "Documented",
    description: "Massive solid beaten copper anthropomorphic figure with curved incurving arms and fish-fin head. Characteristic ritual weapon/emblem of the ancient Gangetic Copper Hoard Culture.",
    imageUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80",
    dateRecorded: "2026-03-29",
    recordedBy: "R. Thorne (Metallurgy Team)"
  },
  {
    id: "IND-2026-023",
    name: "Roman Gold Solidus of Emperor Tiberius",
    type: "Coin",
    material: "Other",
    period: "Classical Indo-Roman Trade",
    site: "Keezhadi",
    excavationArea: "River Port Wharf Trench III",
    layer: "Stratum III (Customs Warehouse Floor)",
    depth: 1.5,
    latitude: 9.8628,
    longitude: 78.1882,
    status: "Documented",
    description: "High-purity Roman gold coin (solidus) of Tiberius (14–37 CE) bearing laureate head on obverse; slash mark incision confirming bullion testing by ancient Tamil guild merchants.",
    imageUrl: "https://images.unsplash.com/photo-1610375461246-83df859d849d?auto=format&fit=crop&w=800&q=80",
    dateRecorded: "2026-03-30",
    recordedBy: "M. Vance (Numismatics Specialist)"
  },
  {
    id: "IND-2026-024",
    name: "Sun Temple Chlorite Wheel Hub Fragment",
    type: "Sculpture",
    material: "Stone",
    period: "Medieval (Ganga Dynasty c. 1250 CE)",
    site: "Sisupalgarh",
    excavationArea: "Eastern Gateway Platform",
    layer: "Stratum II (Medieval Temple Debris)",
    depth: 0.8,
    latitude: 20.2970,
    longitude: 85.8265,
    status: "Documented",
    description: "Finely carved green chlorite stone spoke hub decorated with dancers, musicians, and beaded scrollwork from an architectural sun chariot ensemble.",
    imageUrl: "https://images.unsplash.com/photo-1549887534-1541e9326642?auto=format&fit=crop&w=800&q=80",
    dateRecorded: "2026-04-01",
    recordedBy: "Dr. K. Rath (Iconography Lead)"
  }
];

// Color mapping for Artifact Types across GIS, Charts, and Badges
const TYPE_CONFIG = {
  Pottery: { color: "#B84A2A", bg: "rgba(184, 74, 42, 0.18)", text: "#F39C72", icon: "fa-wine-bottle", label: "Mrit-Patra (Pottery)" },
  Coin: { color: "#D4AF37", bg: "rgba(212, 175, 55, 0.18)", text: "#FAD02C", icon: "fa-coins", label: "Mudrā (Coins)" },
  Sculpture: { color: "#8E44AD", bg: "rgba(142, 68, 173, 0.18)", text: "#BB8FCE", icon: "fa-monument", label: "Mūrti (Sculpture)" },
  Tool: { color: "#175873", bg: "rgba(23, 88, 115, 0.18)", text: "#5DADE2", icon: "fa-hammer", label: "Ayudha (Tools)" },
  Jewelry: { color: "#C0392B", bg: "rgba(192, 57, 43, 0.18)", text: "#F1948A", icon: "fa-gem", label: "Abharaṇa (Jewelry)" },
  Inscription: { color: "#27AE60", bg: "rgba(39, 174, 96, 0.18)", text: "#58D68D", icon: "fa-scroll", label: "Shilālekha (Inscriptions)" },
  Brick: { color: "#E67E22", bg: "rgba(230, 126, 34, 0.18)", text: "#F5B041", icon: "fa-cubes", label: "Ishtikā (Bricks)" },
  Other: { color: "#7F8C8D", bg: "rgba(127, 140, 141, 0.18)", text: "#BDC3C7", icon: "fa-layer-group", label: "Anyat (Other)" }
};

const MATERIAL_CONFIG = {
  Terracotta: { color: "#B84A2A" },
  Stone: { color: "#8C7B6C" },
  Clay: { color: "#B38F6B" },
  Bronze: { color: "#CD7F32" },
  Iron: { color: "#5D6D7E" },
  Copper: { color: "#B87333" },
  Other: { color: "#D4AF37" }
};

const PERIOD_CONFIG = {
  "Harappan (Indus Valley)": { color: "#B84A2A" },
  "Vedic & Mahajanapada": { color: "#9B59B6" },
  "Mauryan (c. 300 BCE)": { color: "#D4AF37" },
  "Shunga-Satavahana": { color: "#E67E22" },
  "Gupta Classical (c. 400 CE)": { color: "#F39C12" },
  "Chola Imperial (c. 1050 CE)": { color: "#16A085" },
  "Vijayanagara (c. 1500 CE)": { color: "#2980B9" },
  "Colonial": { color: "#7F8C8D" }
};

const SITE_CONFIG = {
  "Dholavira": { name: "Dholavira & Lothal (Indus Valley Citadel)", center: [23.8864, 70.2135], desc: "Kutch Bronze Age metropolis with stone fortification, monumental reservoirs, and lapidary bead workshops." },
  "Sisupalgarh": { name: "Sisupalgarh & Dhauli (Ancient Kalinga)", center: [20.2965, 85.8255], desc: "Square fortified urban citadel with stone bastions, Mauryan NBPW pottery, and Ashokan Major Rock Edicts." },
  "Sanchi": { name: "Sanchi & Vidisha (Great Stupa Complex)", center: [23.4795, 77.7397], desc: "UNESCO World Heritage Mauryan Buddhist stupas, ornate red sandstone torana gateways, and Heliodorus pillar." },
  "Nalanda": { name: "Nalanda Mahavihara (Ancient Monastic University)", center: [25.1358, 85.4455], desc: "Celebrated ancient university monasteries, monastic clay bulla seals, and sacred Pala bronze ateliers." },
  "Hampi": { name: "Hampi / Vijayanagara (Imperial Capital)", center: [15.3350, 76.4600], desc: "14th-century capital on Tungabhadra banks with monolithic chariot shrines, royal bazaars, and gold coin mints." },
  "Keezhadi": { name: "Keezhadi (Sangam Era Vaigai Valley)", center: [9.8625, 78.1885], desc: "Sangam urban settlement proving 6th-century BCE Tamil-Brahmi literacy, brick weaving vats, and Roman trade." }
};
